Repository COS301-SE-2022/PaWdopt, pull requests merged in 2022-05, with the labels that each got.

#10 📝 Fixed link to project board
  README.md
Labels: priority:low, status:ready, type:change, scope:client

#8 Initialisation of NX framework
  .editorconfig
  .eslintrc.json
  .gitignore
  .prettierignore
  .prettierrc
  .vscode/extensions.json
  apps/.gitkeep
  apps/pawdopt-e2e/.eslintrc.json
  apps/pawdopt-e2e/cypress.json
  apps/pawdopt-e2e/project.json
  apps/pawdopt-e2e/src/fixtures/example.json
  apps/pawdopt-e2e/src/integration/app.spec.ts
  apps/pawdopt-e2e/src/support/app.po.ts
  apps/pawdopt-e2e/src/support/commands.ts
  apps/pawdopt-e2e/src/support/index.ts
  apps/pawdopt-e2e/tsconfig.json
  apps/pawdopt/.browserslistrc
  apps/pawdopt/.eslintrc.json
  apps/pawdopt/.gitignore
  apps/pawdopt/capacitor.config.ts
  apps/pawdopt/ionic.config.json
  apps/pawdopt/jest.config.ts
  apps/pawdopt/project.json
  apps/pawdopt/src/app/app-routing.module.ts
  apps/pawdopt/src/app/app.component.html
  apps/pawdopt/src/app/app.component.scss
  apps/pawdopt/src/app/app.component.spec.ts
  apps/pawdopt/src/app/app.component.ts
  apps/pawdopt/src/app/app.module.ts
  apps/pawdopt/src/app/home/home-routing.module.ts
  apps/pawdopt/src/app/home/home.module.ts
  apps/pawdopt/src/app/home/home.page.html
  apps/pawdopt/src/app/home/home.page.scss
  apps/pawdopt/src/app/home/home.page.ts
  apps/pawdopt/src/app/nx-welcome.component.ts
  apps/pawdopt/src/assets/.gitkeep
  apps/pawdopt/src/assets/icon/favicon.png
  apps/pawdopt/src/assets/shapes.svg
  apps/pawdopt/src/environments/environment.prod.ts
  apps/pawdopt/src/environments/environment.ts
  apps/pawdopt/src/index.html
  apps/pawdopt/src/main.ts
  apps/pawdopt/src/polyfills.ts
  apps/pawdopt/src/styles.scss
  apps/pawdopt/src/test-setup.ts
  apps/pawdopt/src/theme/variables.scss
  apps/pawdopt/tsconfig.app.json
  apps/pawdopt/tsconfig.editor.json
  apps/pawdopt/tsconfig.json
  apps/pawdopt/tsconfig.spec.json
  jest.config.ts
  jest.preset.ts
  libs/.gitkeep
  nx.json
  package.json
  tools/generators/.gitkeep
  tools/tsconfig.tools.json
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: priority:medium, status:not-ready, type:addition

#16 ⬇️ (Dependencies): Upgraded and corrected dependencies
  package.json
  yarn.lock
Labels: priority:low, status:ready, type:change, type:enhance, scope:repository

#21 🚀(Routing-Signup): Added routing for signup page
  apps/pawdopt/src/app/app-routing.module.ts
  jest.config.js
  jest.preset.js
  libs/mobile/signup/feature/.babelrc
  libs/mobile/signup/feature/.eslintrc.json
  libs/mobile/signup/feature/README.md
  libs/mobile/signup/feature/jest.config.js
  libs/mobile/signup/feature/project.json
  libs/mobile/signup/feature/src/index.ts
  libs/mobile/signup/feature/src/lib/signup-routing.module.ts
  libs/mobile/signup/feature/src/lib/signup.module.ts
  libs/mobile/signup/feature/src/lib/signup.page.html
  libs/mobile/signup/feature/src/lib/signup.page.scss
  libs/mobile/signup/feature/src/lib/signup.page.ts
  libs/mobile/signup/feature/tsconfig.json
  libs/mobile/signup/feature/tsconfig.lib.json
  libs/mobile/signup/feature/tsconfig.spec.json
  package.json
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: priority:high, status:ready, scope:ui, type:addition

#22 💄 (Styling-global): Added styling for forms and buttons
  apps/pawdopt/src/theme/variables.scss
  libs/mobile/signup/feature/src/lib/signup.page.scss
  libs/mobile/signup/feature/src/lib/signup.page.ts
  libs/shared/styles/global.scss
Labels: priority:high, status:ready, type:change, scope:ui, type:addition

#26 🎨 (Login): Improved layout, Added Logo, Improved Responsive Design
  apps/pawdopt/src/app/app-routing.module.ts
  apps/pawdopt/src/theme/variables.scss
  jest.config.ts
  libs/mobile/login/feature/.babelrc
  libs/mobile/login/feature/.eslintrc.json
  libs/mobile/login/feature/README.md
  libs/mobile/login/feature/jest.config.js
  libs/mobile/login/feature/project.json
  libs/mobile/login/feature/src/assets/PaWdopt_transparent.png
  libs/mobile/login/feature/src/index.ts
  libs/mobile/login/feature/src/lib/login-routing.module.ts
  libs/mobile/login/feature/src/lib/login.module.ts
  libs/mobile/login/feature/src/lib/login.page.html
  libs/mobile/login/feature/src/lib/login.page.scss
  libs/mobile/login/feature/src/lib/login.page.ts
  libs/mobile/login/feature/tsconfig.json
  libs/mobile/login/feature/tsconfig.lib.json
  libs/mobile/login/feature/tsconfig.spec.json
  package.json
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: priority:low, type:enhance, scope:ui

#30 Removed unused dependencies and files
  apps/pawdopt/src/app/nx-welcome.component.ts
  package.json
  yarn.lock
Labels: priority:low, status:ready, type:change, scope:repository

#33 Dependency and gitignore changes
  .gitignore
  apps/pawdopt/package.json
Labels: priority:low, status:ready, type:change, scope:repository

#34 🚀 🔥 ✨ 💄 (UI): Added add dog page
  apps/pawdopt/src/app/app-routing.module.ts
  apps/pawdopt/src/app/home/home.module.ts
  apps/pawdopt/src/main.ts
  apps/pawdopt/src/theme/variables.scss
  libs/mobile/adddog/feature/.babelrc
  libs/mobile/adddog/feature/.eslintrc.json
  libs/mobile/adddog/feature/README.md
  libs/mobile/adddog/feature/jest.config.js
  libs/mobile/adddog/feature/project.json
  libs/mobile/adddog/feature/src/index.ts
  libs/mobile/adddog/feature/src/lib/adddog-routing.module.ts
  libs/mobile/adddog/feature/src/lib/adddog.module.ts
  libs/mobile/adddog/feature/src/lib/adddog.page.html
  libs/mobile/adddog/feature/src/lib/adddog.page.scss
  libs/mobile/adddog/feature/src/lib/adddog.page.ts
  libs/mobile/adddog/feature/tsconfig.json
  libs/mobile/adddog/feature/tsconfig.lib.json
  libs/mobile/adddog/feature/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: priority:medium, status:not-ready, scope:ui, type:addition

#35 Created Dashboard and added functionality
  apps/pawdopt/src/app/app-routing.module.ts
  libs/mobile/dashboard/feature/.babelrc
  libs/mobile/dashboard/feature/.eslintrc.json
  libs/mobile/dashboard/feature/README.md
  libs/mobile/dashboard/feature/jest.config.js
  libs/mobile/dashboard/feature/project.json
  libs/mobile/dashboard/feature/src/index.ts
  libs/mobile/dashboard/feature/src/lib/dashboard-routing.module.ts
  libs/mobile/dashboard/feature/src/lib/dashboard.module.ts
  libs/mobile/dashboard/feature/src/lib/dashboard.page.html
  libs/mobile/dashboard/feature/src/lib/dashboard.page.scss
  libs/mobile/dashboard/feature/src/lib/dashboard.page.ts
  libs/mobile/dashboard/feature/tsconfig.json
  libs/mobile/dashboard/feature/tsconfig.lib.json
  libs/mobile/dashboard/feature/tsconfig.spec.json
  package.json
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: enhancement, priority:high, status:not-ready, scope:ui

#37 Added Initial Cypress Tests for UI
  apps/pawdopt-e2e/cypress.json
  apps/pawdopt-e2e/src/integration/app.spec.ts
  apps/pawdopt-e2e/src/support/app.po.ts
  apps/pawdopt-e2e/src/support/commands.ts
  apps/pawdopt/src/app/home/home.page.html
  libs/mobile/adddog/feature/src/lib/adddog.page.html
  libs/mobile/adddog/feature/src/lib/adddog.page.ts
  libs/mobile/addorg/feature/src/lib/addorg.page.html
  libs/mobile/dashboard/feature/src/lib/dashboard.page.html
  libs/mobile/login/feature/src/lib/login.page.html
  libs/mobile/signup/feature/src/lib/signup.page.html
Labels: status:ready, type:test, scope:client, scope:ui

#38 ✅ 🐛 (Testing): Updated some erroneous code related to tests
  apps/pawdopt-e2e/src/integration/app.spec.ts
  libs/mobile/adddog/feature/src/lib/adddog.page.ts
  libs/mobile/addorg/feature/src/lib/addorg.page.html
  libs/mobile/addorg/feature/src/lib/addorg.page.ts
  libs/mobile/dashboard/feature/src/lib/dashboard.page.html
  libs/mobile/dashboard/feature/src/lib/dashboard.page.ts
Labels: status:ready, type:test, scope:client, scope:ui

#58 ✨ (CI): Added workflows test
  .github/workflows/index.yml
  .github/workflows/nxtest.yml
Labels: status:need-tests, scope:cicd, type:addition

#59 🔥 (CI): Removed codecov
  .github/workflows/nxtest.yml
Labels: status:not-ready, scope:cicd

#54 Completed API creation without queries
  apps/backend/.eslintrc.json
  apps/backend/jest.config.ts
  apps/backend/project.json
  apps/backend/src/app/.gitkeep
  apps/backend/src/app/app.controller.spec.ts
  apps/backend/src/app/app.controller.ts
  apps/backend/src/app/app.module.ts
  apps/backend/src/app/app.service.spec.ts
  apps/backend/src/app/app.service.ts
  apps/backend/src/assets/.gitkeep
  apps/backend/src/environments/environment.prod.ts
  apps/backend/src/environments/environment.ts
  apps/backend/src/main.ts
  apps/backend/tsconfig.app.json
  apps/backend/tsconfig.json
  apps/backend/tsconfig.spec.json
  libs/backend/shell/api/feature/.eslintrc.json
  libs/backend/shell/api/feature/README.md
  libs/backend/shell/api/feature/jest.config.ts
  libs/backend/shell/api/feature/project.json
  libs/backend/shell/api/feature/src/index.ts
  libs/backend/shell/api/feature/src/lib/api.dto.ts
  libs/backend/shell/api/feature/src/lib/api.resolver.ts
  libs/backend/shell/api/feature/src/lib/api.schema.ts
  libs/backend/shell/api/feature/src/lib/api.service.ts
  libs/backend/shell/api/feature/src/lib/backend-shell-api-feature.module.ts
  libs/backend/shell/api/feature/tsconfig.json
  libs/backend/shell/api/feature/tsconfig.lib.json
  libs/backend/shell/api/feature/tsconfig.spec.json
  package.json
  schema.gql
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: priority:high, status:ready, status:need-tests, api, scope:api, type:addition

#56 Added Mongo Docker Script
  .env
  docker-compose.yml
  package.json
  yarn.lock
Labels: priority:medium, status:ready, db, scope:db, scope:repository, type:addition

#60 ✅ (CI): Test worklfow
  .github/workflows/full.yml
  Test.txt
Labels: priority:low, status:ready, type:test, scope:cicd

#63 ✅ (CI): Added codecov secret token
  .github/workflows/nxtest.yml
  Test.txt
Labels: priority:low, status:ready, type:enhance, scope:cicd

#64 Rayden - staged API schema changes
  libs/backend/shell/api/feature/src/lib/api.dto.ts
  libs/backend/shell/api/feature/src/lib/api.resolver.ts
  libs/backend/shell/api/feature/src/lib/api.schema.ts
  libs/backend/shell/api/feature/src/lib/api.service.ts
  libs/backend/shell/api/feature/src/lib/backend-shell-api-feature.module.ts
Labels: status:not-ready, api

#66 🔥 (CI): Fix the workflow
  package.json
Labels: priority:medium, status:not-ready, type:enhance, scope:cicd

#67 🐛 (CI): Typo in the dependencies
  package.json
Labels: priority:low, status:not-ready, type:change, scope:cicd

#68 🐛(CI): Updated lock file
  yarn.lock
Labels: priority:low, status:not-ready, type:change, scope:cicd

#70 🐛 (CI): Fixed workflow
  .github/workflows/full.yml
  .github/workflows/index.yml
  package.json
Labels: priority:high, status:ready, type:enhance, scope:cicd

#71 🔥 (CI): Updated lock
  yarn.lock
Labels: priority:low, priority:high, status:not-ready, type:enhance, scope:cicd

#73 ✨ (CI): Updated Typescript
  package.json
  yarn.lock
Labels: priority:high, status:ready, type:enhance, scope:cicd

#74 ✅ (Testing): Corrected default tests
  apps/backend/src/app/app.controller.spec.ts
  apps/backend/src/app/app.service.spec.ts
  apps/pawdopt/src/app/app.component.spec.ts
Labels: status:ready, type:enhance, type:test, scope:cicd

#76 🚀 🚧 DB: Created classes
  libs/backend/shell/api/feature/src/lib/api.schema.ts
Labels: priority:high, status:ready, scope:db, type:addition

#77 Alex
  libs/backend/shell/api/feature/src/lib/api.dto.ts
  libs/backend/shell/api/feature/src/lib/api.resolver.ts
  libs/backend/shell/api/feature/src/lib/api.schema.ts
  libs/backend/shell/api/feature/src/lib/api.service.ts
  libs/backend/shell/api/feature/src/lib/backend-shell-api-feature.module.ts
  package.json
  yarn.lock
Labels: priority:high, status:not-ready, db, api
