Repository COS301-SE-2022/PaWdopt, pull requests merged in 2022-09, with the labels that each got.

#181 (Signup) UI fix - Back button and (Addorg) - fix back button
  libs/mobile/addorg/feature/src/lib/addorg.page.html
  libs/mobile/addorg/feature/src/lib/addorg.page.scss
  libs/mobile/signup/feature/src/lib/signup.page.html
  libs/mobile/signup/feature/src/lib/signup.page.scss
Labels: status:ready, 0-1 Hours

#211 💄 ⚙️ Fixes for dashboard and adddog
  libs/mobile/adddog/feature/src/lib/adddog.page.html
  libs/mobile/adddog/feature/src/lib/adddog.page.scss
  libs/mobile/adddog/feature/src/lib/adddog.page.ts
  libs/mobile/dashboard/feature/src/lib/dashboard.page.html
  libs/mobile/dashboard/feature/src/lib/dashboard.page.scss
  libs/mobile/dashboard/feature/src/lib/dashboard.page.ts
Labels: priority:high, 1-3 Hours, Easy, Moderate

#212 💄 ⚙️ (updateorremove) - UI fixes and (Addog) - Compulsory form fields
  libs/mobile/adddog/feature/src/lib/adddog.page.html
  libs/mobile/adddog/feature/src/lib/adddog.page.ts
  libs/mobile/updateorremovedog/feature/src/lib/updateorremovedog.page.html
  libs/mobile/updateorremovedog/feature/src/lib/updateorremovedog.page.scss
  libs/mobile/updateorremovedog/feature/src/lib/updateorremovedog.page.ts
Labels: priority:high, 1-3 Hours, Easy, Moderate

#213 Hosting 🚧 : added some hosting files
  .firebase/hosting.ZGlzdFxhcHBzXGJhY2tlbmQ.cache
  .firebaserc
  .gitignore
  firebase.json
  storage.rules
Labels: priority:high, status:not-ready

#215 🚀 (FireBase) Auto deploy with git actions
  .firebase/hosting.ZGlzdFxhcHBzXGJhY2tlbmQ.cache
  .github/workflows/firebase-hosting-merge.yml
  firebase.json
  remoteconfig.template.json
Labels: priority:medium, status:need-tests, New Feature

#219 💄 ⚙️ User info and Owned dogs UI fixes
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.html
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.scss
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts
  libs/mobile/userinfo/feature/src/lib/userinfo.page.html
  libs/mobile/userinfo/feature/src/lib/userinfo.page.scss
Labels: priority:medium, 0-1 Hours, 1-3 Hours, Easy

#218 (Login) ✨ : Added Google sign in functionality
  libs/backend/shell/api/feature/src/lib/api.service.ts
  libs/mobile/login/feature/src/lib/login.page.html
  libs/mobile/login/feature/src/lib/login.page.ts
Labels: priority:medium, status:ready, API, UI

#223 ⚙️ 💄 UI Fixes according to feedback
  apps/pawdopt/src/theme/variables.scss
  libs/mobile/adddog/feature/src/lib/adddog.page.html
  libs/mobile/updateorremovedog/feature/src/lib/updateorremovedog.page.html
  libs/mobile/updateorremovedog/feature/src/lib/updateorremovedog.page.ts
Labels: priority:medium, 1-3 Hours

#225 :lipstick: Chat Page UI - Baseline done
  libs/mobile/chat/feature/src/lib/chat.module.ts
  libs/mobile/chat/feature/src/lib/chat.page.html
  libs/mobile/chat/feature/src/lib/chat.page.scss
  libs/mobile/chat/feature/src/lib/chat.page.ts
  package.json
  yarn.lock
Labels: status:not-ready, 1-3 Hours, Moderate, UI, New Feature

#222 added geolocate and did some validation
  apps/pawdopt/src/app/app.module.ts
  libs/backend/shell/api/feature/src/lib/api.dto.ts
  libs/backend/shell/api/feature/src/lib/api.schema.ts
  libs/backend/shell/api/feature/src/lib/api.service.spec.ts
  libs/mobile/addorg/feature/src/lib/addorg.page.html
  libs/mobile/addorg/feature/src/lib/addorg.page.ts
  libs/mobile/signup/feature/src/lib/signup.page.html
  libs/mobile/signup/feature/src/lib/signup.page.ts
  package.json
  schema.gql
  yarn.lock
Labels: status:need-tests, 3+ Hours, Moderate, Bug Fix, New Feature, Changes

#226 🐛 (Workflow) Updated run jobs
  .github/workflows/firebase-hosting-merge.yml
Labels: priority:medium, status:ready, Moderate, Bug Fix

#229 :lipstick: Basic UI for Appointment Page
  libs/mobile/appointmentpage/feature/src/lib/appointmentpage.module.ts
  libs/mobile/appointmentpage/feature/src/lib/appointmentpage.page.html
  libs/mobile/appointmentpage/feature/src/lib/appointmentpage.page.scss
  libs/mobile/appointmentpage/feature/src/lib/appointmentpage.page.ts
Labels: status:not-ready, 0-1 Hours, Easy, UI

#230 ✨ (OwnedDogs) Added breed
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.html
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts
Labels: priority:low, status:need-tests, UI

#232 updating the location
  libs/mobile/addorg/feature/src/lib/addorg.page.html
  libs/mobile/addorg/feature/src/lib/addorg.page.ts
  package.json
  schema.gql
  yarn.lock
Labels: status:ready, New Feature

#234 Quick addorg fix
  libs/mobile/addorg/feature/src/lib/addorg.page.ts
Labels: API

#235 🐛 Adddog, Addorg, Dashboard, Owneddogs, Userinfo fixed
  apps/backend/src/main.ts
  libs/mobile/adddog/feature/src/lib/adddog.page.html
  libs/mobile/adddog/feature/src/lib/adddog.page.ts
  libs/mobile/addorg/feature/src/lib/addorg.page.html
  libs/mobile/addorg/feature/src/lib/addorg.page.scss
  libs/mobile/addorg/feature/src/lib/addorg.page.ts
  libs/mobile/dashboard/feature/src/lib/dashboard.page.html
  libs/mobile/dashboard/feature/src/lib/dashboard.page.ts
  libs/mobile/login/feature/src/lib/login.page.ts
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts
  libs/mobile/signup/feature/src/lib/signup.page.ts
  libs/mobile/userinfo/feature/src/lib/userinfo.page.ts
Labels: DB, API, UI

#236 🐛 Minor changes and added loaders
  .github/workflows/firebase-hosting-merge.yml
  apps/pawdopt/project.json
  apps/pawdopt/src/app/app-routing.module.ts
  apps/pawdopt/src/app/home/home.page.ts
  libs/mobile/add-org-member/feature/.babelrc
  libs/mobile/add-org-member/feature/.eslintrc.json
  libs/mobile/add-org-member/feature/README.md
  libs/mobile/add-org-member/feature/jest.config.ts
  libs/mobile/add-org-member/feature/project.json
  libs/mobile/add-org-member/feature/src/index.ts
  libs/mobile/add-org-member/feature/src/lib/mobile-add-org-member-feature.spec.ts
  libs/mobile/add-org-member/feature/src/lib/mobile-add-org-member-feature.ts
  libs/mobile/add-org-member/feature/tsconfig.json
  libs/mobile/add-org-member/feature/tsconfig.lib.json
  libs/mobile/add-org-member/feature/tsconfig.spec.json
  libs/mobile/adddog/feature/src/lib/adddog.page.html
  libs/mobile/adddog/feature/src/lib/adddog.page.ts
  libs/mobile/chat/feature/src/lib/chat.page.ts
  libs/mobile/chatlist/feature/src/lib/chatlist.page.html
  libs/mobile/chatlist/feature/src/lib/chatlist.page.ts
  libs/mobile/dashboard/feature/src/lib/dashboard.page.html
  libs/mobile/dashboard/feature/src/lib/dashboard.page.ts
  libs/mobile/login/feature/src/lib/login.page.html
  libs/mobile/login/feature/src/lib/login.page.ts
  libs/mobile/orgsettings/feature/src/lib/orgsettings.page.ts
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.html
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts
  libs/mobile/signup/feature/src/lib/signup.page.ts
  libs/mobile/uikit/feature/.babelrc
  libs/mobile/uikit/feature/.eslintrc.json
  libs/mobile/uikit/feature/README.md
  libs/mobile/uikit/feature/jest.config.js
  libs/mobile/uikit/feature/project.json
  libs/mobile/uikit/feature/src/index.ts
  libs/mobile/uikit/feature/src/lib/uikit-routing.module.ts
  libs/mobile/uikit/feature/src/lib/uikit.module.ts
  libs/mobile/uikit/feature/src/lib/uikit.page.html
  libs/mobile/uikit/feature/src/lib/uikit.page.scss
  libs/mobile/uikit/feature/src/lib/uikit.page.ts
  libs/mobile/uikit/feature/tsconfig.json
  libs/mobile/uikit/feature/tsconfig.lib.json
  libs/mobile/uikit/feature/tsconfig.spec.json
  libs/mobile/updateorremovedog/feature/src/lib/updateorremovedog.page.ts
  libs/mobile/uploaddoc/feature/src/lib/uploaddoc.page.ts
  libs/mobile/userinfo/feature/src/lib/userinfo.page.html
  libs/mobile/userinfo/feature/src/lib/userinfo.page.ts
  libs/mobile/userlikes/feature/src/lib/userlikes.page.html
  libs/mobile/userlikes/feature/src/lib/userlikes.page.ts
  libs/mobile/userprofile/feature/src/lib/userprofile.page.ts
  tsconfig.base.json
  workspace.json
Labels: priority:medium, status:ready, Easy, Bug Fix, Changes

#237 🐛 ✨ Many changes adoption process almost ready
  apps/pawdopt/src/app/home/home.page.ts
  libs/backend/shell/api/feature/src/lib/api.dto.ts
  libs/backend/shell/api/feature/src/lib/api.resolver.ts
  libs/backend/shell/api/feature/src/lib/api.schema.ts
  libs/backend/shell/api/feature/src/lib/api.service.ts
  libs/backend/shell/api/feature/src/lib/backend-shell-api-feature.module.ts
  libs/mobile/adoptionprocess/feature/src/lib/adoptionprocess.page.html
  libs/mobile/adoptionprocess/feature/src/lib/adoptionprocess.page.ts
  libs/mobile/chat/feature/src/lib/chat.page.html
  libs/mobile/chat/feature/src/lib/chat.page.ts
  libs/mobile/dashboard/feature/src/lib/dashboard.page.ts
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts
  libs/mobile/useradoption/feature/src/lib/useradoption.page.html
  libs/mobile/useradoption/feature/src/lib/useradoption.page.ts
  schema.gql
Labels: DB, API, UI

#238 Quick UI fixes
  libs/mobile/appointmentpage/feature/src/lib/appointmentpage.page.html
  libs/mobile/appointmentpage/feature/src/lib/appointmentpage.page.ts
  libs/mobile/chat/feature/src/lib/chat.page.html
  libs/mobile/chat/feature/src/lib/chat.page.scss
  libs/mobile/useradoption/feature/src/lib/useradoption.page.html
Labels: priority:low, 0-1 Hours, Easy

#239 Adoption process changes + chat working fully
  apps/pawdopt/src/app/home/home.page.html
  apps/pawdopt/src/app/home/home.page.ts
  libs/backend/shell/api/feature/src/lib/api.dto.ts
  libs/backend/shell/api/feature/src/lib/api.resolver.ts
  libs/backend/shell/api/feature/src/lib/api.service.ts
  libs/mobile/chat/feature/src/lib/chat.page.ts
  libs/mobile/chatlist/feature/src/lib/chatlist.page.html
  libs/mobile/chatlist/feature/src/lib/chatlist.page.ts
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.html
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts
  libs/mobile/useradoption/feature/src/lib/useradoption.page.ts
  schema.gql
Labels: 3+ Hours, Difficult, Easy, Moderate, DB, API, UI, Bug Fix, Changes

#240 Quick routing issues
  libs/mobile/chat/feature/src/lib/chat.page.ts
  libs/mobile/chatlist/feature/src/lib/chatlist.page.ts
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.ts
  libs/mobile/updateorremovedog/feature/src/lib/updateorremovedog.page.ts
  libs/mobile/userlikes/feature/src/lib/userlikes.page.html
  libs/mobile/userlikes/feature/src/lib/userlikes.page.ts
  libs/mobile/userprofile/feature/src/lib/userprofile.page.html
  libs/mobile/userprofile/feature/src/lib/userprofile.page.ts
Labels: priority:high, 0-1 Hours, Easy, Bug Fix

#241 Added config for maps api key
  .gitignore
  apps/pawdopt/src/app/app.module.ts
  apps/pawdopt/src/app/home/home.page.ts
  libs/config/index.ts
  libs/mobile/addorg/feature/src/lib/addorg.page.ts
  tsconfig.base.json
Labels: API

#242 Added base for upload docs
  apps/backend/src/app/app.module.ts
  apps/pawdopt/tsconfig.app.json
  libs/mobile/appointmentpage/feature/src/lib/appointmentpage.page.html
  libs/mobile/appointmentpage/feature/src/lib/appointmentpage.page.ts
  libs/mobile/chat/feature/src/lib/chat.page.ts
  libs/mobile/uploaddoc/feature/src/lib/uploaddoc.page.html
  libs/mobile/uploaddoc/feature/src/lib/uploaddoc.page.scss
  libs/mobile/uploaddoc/feature/src/lib/uploaddoc.page.ts
  libs/mobile/userprofile/feature/src/lib/userprofile.page.html
  libs/mobile/userprofile/feature/src/lib/userprofile.page.ts
  package.json
  yarn.lock
Labels: 0-1 Hours, Difficult, DB, Changes

#243 Added distance based filter and created stats schema
  apps/pawdopt/src/app/app.module.ts
  apps/pawdopt/src/app/home/home.page.ts
  apps/pawdopt/src/environments/environment.prod.ts
  libs/backend/shell/api/feature/src/lib/api.dto.ts
  libs/backend/shell/api/feature/src/lib/api.resolver.ts
  libs/backend/shell/api/feature/src/lib/api.schema.ts
  libs/backend/shell/api/feature/src/lib/api.service.ts
  libs/backend/shell/api/feature/src/lib/backend-shell-api-feature.module.ts
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.html
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.ts
  libs/mobile/uploaddoc/feature/src/lib/uploaddoc.page.html
  libs/mobile/uploaddoc/feature/src/lib/uploaddoc.page.ts
  package.json
  schema.gql
  yarn.lock
Labels: status:need-tests, 3+ Hours

#244 Rayden
  libs/backend/shell/api/feature/src/lib/api.dto.ts
  libs/backend/shell/api/feature/src/lib/api.resolver.ts
  libs/backend/shell/api/feature/src/lib/api.schema.ts
  libs/backend/shell/api/feature/src/lib/api.service.ts
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.html
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.scss
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.ts
  libs/mobile/uploaddoc/feature/src/lib/uploaddoc.page.ts
  schema.gql
Labels: priority:high, status:not-ready, New Feature

#245 Small fixes before demo
  libs/backend/shell/api/feature/src/lib/api.service.ts
  libs/mobile/appointmentpage/feature/src/lib/appointmentpage.page.ts
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts
  libs/mobile/updateorremovedog/feature/src/lib/updateorremovedog.page.html
  libs/mobile/updateorremovedog/feature/src/lib/updateorremovedog.page.ts
  libs/mobile/uploaddoc/feature/src/lib/uploaddoc.page.html
  libs/mobile/uploaddoc/feature/src/lib/uploaddoc.page.ts
  libs/mobile/userinfo/feature/src/lib/userinfo.page.html
  libs/mobile/userinfo/feature/src/lib/userinfo.page.ts
Labels: status:not-ready, 1-3 Hours, Bug Fix

#247 Added small fixes to org profile 🐛
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.ts
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts
Labels: priority:high, status:ready, 0-1 Hours, Easy

#248 Rayden
  apps/pawdopt/src/app/home/home.page.html
  apps/pawdopt/src/app/home/home.page.ts
  libs/backend/shell/api/feature/src/lib/api.resolver.ts
  libs/backend/shell/api/feature/src/lib/api.service.ts
  libs/mobile/adddog/feature/src/lib/adddog.page.ts
  libs/mobile/adoptionprocess/feature/src/lib/adoptionprocess.page.ts
  libs/mobile/dashboard/feature/src/lib/dashboard.page.ts
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.html
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.ts
  libs/mobile/orgsettings/feature/src/lib/orgsettings.page.html
  libs/mobile/orgsettings/feature/src/lib/orgsettings.page.scss
  libs/mobile/orgsettings/feature/src/lib/orgsettings.page.ts
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.html
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts
  libs/mobile/signup/feature/src/lib/signup.page.html
  libs/mobile/signup/feature/src/lib/signup.page.ts
  libs/mobile/updateorremovedog/feature/src/lib/updateorremovedog.page.html
  libs/mobile/updateorremovedog/feature/src/lib/updateorremovedog.page.ts
  libs/mobile/uploaddoc/feature/src/lib/uploaddoc.page.ts
  libs/mobile/useradoption/feature/src/lib/useradoption.page.html
  libs/mobile/useradoption/feature/src/lib/useradoption.page.ts
  libs/mobile/userinfo/feature/src/lib/userinfo.page.html
  schema.gql
Labels: status:not-ready, 3+ Hours, Changes

#250 🐛 Small routing fixes
  libs/mobile/adddog/feature/src/lib/adddog.page.ts
  libs/mobile/adoptionprocess/feature/src/lib/adoptionprocess.page.html
  libs/mobile/adoptionprocess/feature/src/lib/adoptionprocess.page.ts
  libs/mobile/appointmentpage/feature/src/lib/appointmentpage.page.html
  libs/mobile/appointmentpage/feature/src/lib/appointmentpage.page.ts
  libs/mobile/dashboard/feature/src/lib/dashboard.page.html
  libs/mobile/dashboard/feature/src/lib/dashboard.page.ts
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.html
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.ts
  libs/mobile/orgsettings/feature/src/lib/orgsettings.page.html
  libs/mobile/orgsettings/feature/src/lib/orgsettings.page.ts
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts
  libs/mobile/preferences/feature/src/lib/preferences.page.html
  libs/mobile/preferences/feature/src/lib/preferences.page.ts
  libs/mobile/updateorremovedog/feature/src/lib/updateorremovedog.page.html
  libs/mobile/updateorremovedog/feature/src/lib/updateorremovedog.page.ts
  libs/mobile/uploaddoc/feature/src/lib/uploaddoc.page.html
  libs/mobile/uploaddoc/feature/src/lib/uploaddoc.page.ts
  libs/mobile/useradoption/feature/src/lib/useradoption.page.html
  libs/mobile/useradoption/feature/src/lib/useradoption.page.ts
  libs/mobile/userinfo/feature/src/lib/userinfo.page.html
  libs/mobile/userinfo/feature/src/lib/userinfo.page.ts
  libs/mobile/userlikes/feature/src/lib/userlikes.page.html
  libs/mobile/userlikes/feature/src/lib/userlikes.page.ts
  libs/mobile/userprofile/feature/src/lib/userprofile.page.html
  libs/mobile/userprofile/feature/src/lib/userprofile.page.ts
Labels: status:ready, 0-1 Hours, Easy

#251 💄 Further UI fixes
  libs/mobile/adddog/feature/src/lib/adddog.page.html
  libs/mobile/adddog/feature/src/lib/adddog.page.scss
  libs/mobile/chatlist/feature/src/lib/chatlist.page.scss
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.html
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.html
Labels: 0-1 Hours, Easy, UI, New Feature

#255 Backend dockerised
  .dockerignore
  Dockerfile
  apps/pawdopt/src/app/app.module.ts
  apps/pawdopt/src/app/home/home.page.ts
  docker-compose.yml
  dockerstarter.sh
  libs/mobile/chatlist/feature/src/lib/chatlist.page.ts
  libs/shared/data-store/.eslintrc.json
  libs/shared/data-store/README.md
  libs/shared/data-store/jest.config.ts
  libs/shared/data-store/project.json
  libs/shared/data-store/src/index.ts
  libs/shared/data-store/src/lib/shared-data-store.module.ts
  libs/shared/data-store/src/lib/vars-store/state/vars.actions.ts
  libs/shared/data-store/src/lib/vars-store/state/vars.effects.spec.ts
  libs/shared/data-store/src/lib/vars-store/state/vars.effects.ts
  libs/shared/data-store/src/lib/vars-store/state/vars.facade.spec.ts
  libs/shared/data-store/src/lib/vars-store/state/vars.facade.ts
  libs/shared/data-store/src/lib/vars-store/state/vars.models.ts
  libs/shared/data-store/src/lib/vars-store/state/vars.reducer.spec.ts
  libs/shared/data-store/src/lib/vars-store/state/vars.reducer.ts
  libs/shared/data-store/src/lib/vars-store/state/vars.selectors.spec.ts
  libs/shared/data-store/src/lib/vars-store/state/vars.selectors.ts
  libs/shared/data-store/src/lib/vars-store/vars-store.module.ts
  libs/shared/data-store/tsconfig.json
  libs/shared/data-store/tsconfig.lib.json
  libs/shared/data-store/tsconfig.spec.json
  package.json
  workspace.json
  yarn.lock
Labels: priority:high, status:not-ready, 3+ Hours, Difficult, API, New Feature

#256 Added Enterprise ID Provision in the UI
  libs/mobile/addorg/feature/src/lib/addorg.page.html
  libs/mobile/addorg/feature/src/lib/addorg.page.ts
Labels: status:not-ready, 0-1 Hours, UI

#258 Rayden
  .github/workflows/full.yml
  .github/workflows/metatest.yml
  apps/pawdopt/src/app/home/home.page.ts
  libs/backend/shell/api/feature/src/lib/api.resolver.ts
  libs/backend/shell/api/feature/src/lib/api.service.ts
  libs/mobile/chat/feature/src/lib/chat.page.ts
  libs/mobile/chatlist/feature/src/lib/chatlist.page.ts
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.html
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.ts
  libs/mobile/useradoption/feature/src/lib/useradoption.page.ts
  libs/mobile/userlikes/feature/src/lib/userlikes.page.ts
  package.json
  schema.gql
  test.txt
  yarn.lock
Labels: priority:high, status:ready, 3+ Hours, Difficult, Bug Fix

#259 (ML): Reupload corrected code
  .gitignore
  ML/.dockerignore
  ML/Dockerfile
  ML/breed_detector.py
  ML/requirements.txt
  ML/server.py
  apps/backend/src/app/app.controller.ts
  apps/backend/src/app/app.module.ts
  libs/shared/ml/feature/.eslintrc.json
  libs/shared/ml/feature/README.md
  libs/shared/ml/feature/jest.config.ts
  libs/shared/ml/feature/project.json
  libs/shared/ml/feature/src/index.ts
  libs/shared/ml/feature/src/lib/shared-ml-feature.module.ts
  libs/shared/ml/feature/src/lib/shared-ml-feature.service.spec.ts
  libs/shared/ml/feature/src/lib/shared-ml-feature.service.ts
  libs/shared/ml/feature/tsconfig.json
  libs/shared/ml/feature/tsconfig.lib.json
  libs/shared/ml/feature/tsconfig.spec.json
  package.json
  tsconfig.base.json
  workspace.json
Labels: priority:high, status:ready, 0-1 Hours, ML, Bug Fix

#261 Unit tests
  libs/backend/shell/api/feature/src/lib/api.service.spec.ts
Labels: priority:high, DB, API

#262 Whitespace in signup and addorg at bottom
  libs/mobile/addorg/feature/src/lib/addorg.page.html
  libs/mobile/signup/feature/src/lib/signup.page.html
  libs/shared/ml/feature/src/lib/shared-ml-feature.service.spec.ts
Labels: priority:low, status:ready, UI

#263 Routing, subscribes, back buttons
  apps/pawdopt/src/app/home/home.page.ts
  libs/mobile/adddog/feature/src/lib/adddog.page.ts
  libs/mobile/addorg/feature/src/lib/addorg.page.ts
  libs/mobile/adoptionprocess/feature/src/lib/adoptionprocess.page.ts
  libs/mobile/appointmentpage/feature/src/lib/appointmentpage.page.ts
  libs/mobile/chat/feature/src/lib/chat.page.html
  libs/mobile/chat/feature/src/lib/chat.page.ts
  libs/mobile/chatlist/feature/src/lib/chatlist.page.html
  libs/mobile/chatlist/feature/src/lib/chatlist.page.ts
  libs/mobile/dashboard/feature/src/lib/dashboard.page.ts
  libs/mobile/login/feature/src/lib/login.page.ts
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.html
  libs/mobile/orgprofile/feature/src/lib/orgprofile.page.ts
  libs/mobile/orgsettings/feature/src/lib/orgsettings.page.html
  libs/mobile/orgsettings/feature/src/lib/orgsettings.page.scss
  libs/mobile/orgsettings/feature/src/lib/orgsettings.page.ts
  libs/mobile/owneddogs/feature/src/lib/owneddogs.page.ts
  libs/mobile/preferences/feature/src/lib/preferences.page.html
  libs/mobile/preferences/feature/src/lib/preferences.page.ts
  libs/mobile/updateorremovedog/feature/src/lib/updateorremovedog.page.ts
  libs/mobile/uploaddoc/feature/src/lib/uploaddoc.page.ts
  libs/mobile/useradoption/feature/src/lib/useradoption.page.ts
  libs/mobile/userinfo/feature/src/lib/userinfo.page.ts
  libs/mobile/userlikes/feature/src/lib/userlikes.page.html
  libs/mobile/userlikes/feature/src/lib/userlikes.page.ts
  libs/mobile/userprofile/feature/src/lib/userprofile.page.html
  libs/mobile/userprofile/feature/src/lib/userprofile.page.ts
Labels: priority:medium, status:need-tests, 1-3 Hours, UI, Bug Fix
